name: Curious Agent Autonomous Cycle
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  generate-avots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Curious Agent
        run: |
          python curious_agent.py

      - name: Write Heartbeat
        run: echo "$(date -u) - Curious Agent heartbeat" >> heartbeat.log

      - name: Commit Curious Logs
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "Curious-Agent"
          git config --global user.email "curious@sovereign.intelligence"
          git add -A
          git commit -m "Curious Agent: new insights integrated 🌱" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/sovereign-codex/Crown-of-Tyme.git HEAD:main
