name: Deploy Crown of Tyme to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
